FLASK_APP=flaskapp

FLASK_SECRET_KEY='I_suggest_you_place_these_3_under_a_new_file_named_".env"_because_you_dont_want_them_in_version_control'
FLASK_ENV=development
FLASK_SQLALCHEMY_DATABASE_URI=sqlite+pysqlite:///:memory: